# Generated by Django 5.1.7 on 2025-03-28 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('yield_start_date', models.DateField()),
                ('yield_end_date', models.DateField()),
                ('yield_avg_kg', models.FloatField()),
                ('fruit_avg_kg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('orientation', models.CharField(blank=True, max_length=50, null=True)),
                ('farm', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nb_plant', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raws', to='core.field')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raws', to='core.fruit')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('nb_fruit', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('badjpg', 'Invalid Image')], default='processing', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.raw')),
            ],
        ),
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plant_fruit', models.FloatField()),
                ('plant_kg', models.FloatField()),
                ('raw_kg', models.FloatField()),
                ('estimated_yield_kg', models.FloatField()),
                ('maturation_grade', models.FloatField(default=0)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('USR', 'User manual estimation'), ('MLI', 'Machine Learning (Image)'), ('MLV', 'Machine Learning (Video)')], default='MLI', max_length=3)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations', to='core.image')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='core.raw')),
            ],
        ),
    ]
