# Generated by Django 5.1.7 on 2025-03-17 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('orientation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('yield_start_date', models.DateField()),
                ('yield_end_date', models.DateField()),
                ('yield_avg_kg', models.FloatField()),
                ('fruit_avg_kg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nb_plant', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raws', to='core.field')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raws', to='core.fruit')),
            ],
        ),
        migrations.CreateModel(
            name='ImageHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=255)),
                ('nb_apfel', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.raw')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plant_apfel', models.FloatField()),
                ('plant_kg', models.FloatField()),
                ('raw_kg', models.FloatField()),
                ('maturation_grade', models.FloatField(default=0)),
                ('id_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='core.imagehistory')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.raw')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryEstimation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('estimated_yield_kg', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='core.raw')),
            ],
        ),
    ]
