# Generated by Django 5.1.7 on 2025-03-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehistory',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
